### ISSUE TITLE
Expose an endpoint that returns the cached status

### ISSUE THREAD

**Issue by sdib** [ycrumeyrolle/HealthCheck#53]
It could be expensive to run the health check too frequently. If the health status is reported through a dashboard, for example, you don't want every request from the dashboard to trigger a health check. Instead, periodically check the system health and cache the status.

**Comment by CESARDELATORRE** [comment]
The end points already support cache.
Do you mean anything else?

**Comment by sdib** [comment]
@CESARDELATORRE you're right I thought it was not yet implemented ! 
Sorry guys
